[package]
name = "bonsai"
version = "0.1.0"
edition = "2024"
authors = ["Luis Schwab <dev@luisschwab.net>"]
description = "A desktop bitcoin wallet with an embedded Utreexo full node"
repository = "https://github.com/luisschwab/bonsai"
readme = "README.md"
license = "MIT"
keywords = ["bitcoin", "wallet", "bdk", "utreexo", "floresta"]

[[bin]]
name = "bonsai"
path = "src/bonsai.rs"

[features]
hot-reloading = ["iced/hot"]

[package.metadata.bundle]
name = "bonsai"
icon = ["assets/icon/bonsai.icns"]

[dependencies]
bdk_floresta = { git = "https://github.com/luisschwab/bdk-floresta", rev = "b558db0ca23f0d358856968f5bc459d541024dcc", default-features = false }
bdk_wallet = { version = "=3.0.0" }
bitcoin = { version = "=0.32.8" }
bitcoin-consensus-encoding = { version = "=1.0.0-rc.3" } # blame: bitcoin-io v0.3.0 (Encodable->Encode/Decodable->Decode)
chrono = { version = "=0.4.44" }
dirs = { version = "=6.0.0" }
hex = { version = "=0.4.3" }
iced = { version = "=0.14.0", features = ["tokio", "image", "qr_code"] }
maxminddb = { version = "=0.28.1", features = ["mmap"] }
memmap2 = { version = "=0.9.10" }
once_cell = { version = "=1.21.4" }
open = { version = "=5.3.5" }
regex = { version = "=1.12.4" }
rustls-webpki = { version = "=0.103.13" }
serde = { version = "=1.0.228", features = ["derive"] }
thiserror = { version = "=2.0.18" }
tokio = { version = "=1.52.3", features = ["full"] }
toml = { version = "=1.1.2" }
tracing = { version = "=0.1.44" }
tracing-appender = { version = "=0.2.4" }
tracing-subscriber = { version = "=0.3.23", features = ["env-filter", "fmt", "time"] }
