on: [pull_request, push]

name: Zizmor

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  zizmor:
    name: zizmor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0

      - name: Run zizmor 🌈
        run: uvx zizmor .
